<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    '@hotwired/turbo' => [
        'version' => '7.3.0',
    ],
    'bootstrap' => [
        'version' => '5.3.3',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.3',
        'type' => 'css',
    ],
    'menu' => [
        'path' => './assets/javascripts/menu.js',
        'entrypoint' => true,
    ],
    'registration' => [
        'path' => './assets/javascripts/registration.js',
        'entrypoint' => true,
    ],
    'recapitulatif' => [
        'path' => './assets/javascripts/adminRecap.js',
        'entrypoint' => true,
    ],
    'reservation' => [
        'path' => './assets/javascripts/userReservation.js',
        'entrypoint' => true,
    ],
    'axios' => [
        'version' => '1.6.8',
    ],
    'delegue' => [
        'path' => './assets/javascripts/delegue.js',
        'entrypoint' => true,
    ],
    'profil' => [
        'path' => './assets/javascripts/profil.js',
        'entrypoint' => true,
    ],
    'userConsultation' => [
        'path' => './assets/javascripts/userConsultation.js',
        'entrypoint' => true,
    ],
    'userModif' => [
        'path' => './assets/javascripts/userModif.js',
        'entrypoint' => true,
    ],
    'adminConsultation' => [
        'path' => './assets/javascripts/adminConsultation.js',
        'entrypoint' => true,
    ],
];
